<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class LanguagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::enableForeignKeyConstraints();
        DB::table('languages')->truncate();
        Schema::disableForeignKeyConstraints();

        $data=[
            ["id" => 1, "name" => "Abkhazian", "endonym" => "аҧсуа бызшәа, аҧсшәа", "abbreviation2" => "ab", "abbreviation3" => "abk", "status"=>1, "position" => 19999 ],
            ["id" => 2, "name" => "Afar", "endonym" => "Afaraf", "abbreviation2" => "aa", "abbreviation3" => "aar", "status"=>1, "position" => 19999 ],
            ["id" => 3, "name" => "Afrikaans", "endonym" => "Afrikaans", "abbreviation2" => "af", "abbreviation3" => "afr", "status"=>1, "position" => 19999 ],
            ["id" => 4, "name" => "Akan", "endonym" => "Akan", "abbreviation2" => "ak", "abbreviation3" => "aka", "status"=>1, "position" => 19999 ],
            ["id" => 5, "name" => "Albanian", "endonym" => "Shqip", "abbreviation2" => "sq", "abbreviation3" => "sqi", "status"=>1, "position" => 19999 ],
            ["id" => 6, "name" => "Amharic", "endonym" => "አማርኛ", "abbreviation2" => "am", "abbreviation3" => "amh", "status"=>1, "position" => 19999 ],
            ["id" => 7, "name" => "Arabic", "endonym" => "العربية", "abbreviation2" => "ar", "abbreviation3" => "ara", "status"=>1, "position" => 19999 ],
            ["id" => 8, "name" => "Aragonese", "endonym" => "aragonés", "abbreviation2" => "an", "abbreviation3" => "arg", "status"=>1, "position" => 19999 ],
            ["id" => 9, "name" => "Armenian", "endonym" => "Հայերեն", "abbreviation2" => "hy", "abbreviation3" => "hye", "status"=>1, "position" => 19999 ],
            ["id" => 10, "name" => "Assamese", "endonym" => "অসমীয়া", "abbreviation2" => "as", "abbreviation3" => "asm", "status"=>1, "position" => 19999 ],
            ["id" => 11, "name" => "Avaric", "endonym" => "авар мацӀ, магӀарул мацӀ", "abbreviation2" => "av", "abbreviation3" => "ava", "status"=>1, "position" => 19999 ],
            ["id" => 12, "name" => "Avestan", "endonym" => "avesta", "abbreviation2" => "ae", "abbreviation3" => "ave", "status"=>1, "position" => 19999 ],
            ["id" => 13, "name" => "Aymara", "endonym" => "aymar aru", "abbreviation2" => "ay", "abbreviation3" => "aym", "status"=>1, "position" => 19999 ],
            ["id" => 14, "name" => "Azerbaijani", "endonym" => "azərbaycan dili", "abbreviation2" => "az", "abbreviation3" => "aze", "status"=>1, "position" => 19999 ],
            ["id" => 15, "name" => "Bambara", "endonym" => "bamanankan", "abbreviation2" => "bm", "abbreviation3" => "bam", "status"=>1, "position" => 19999 ],
            ["id" => 16, "name" => "Bashkir", "endonym" => "башҡорт теле", "abbreviation2" => "ba", "abbreviation3" => "bak", "status"=>1, "position" => 19999 ],
            ["id" => 17, "name" => "Basque", "endonym" => "euskara, euskera", "abbreviation2" => "eu", "abbreviation3" => "eus", "status"=>1, "position" => 19999 ],
            ["id" => 18, "name" => "Belarusian", "endonym" => "беларуская мова", "abbreviation2" => "be", "abbreviation3" => "bel", "status"=>1, "position" => 19999 ],
            ["id" => 19, "name" => "Bengali", "endonym" => "বাংলা", "abbreviation2" => "bn", "abbreviation3" => "ben", "status"=>1, "position" => 19999 ],
            ["id" => 20, "name" => "Bihari languages", "endonym" => "भोजपुरी", "abbreviation2" => "bh", "abbreviation3" => "bih", "status"=>1, "position" => 19999 ],
            ["id" => 21, "name" => "Bislama", "endonym" => "Bislama", "abbreviation2" => "bi", "abbreviation3" => "bis", "status"=>1, "position" => 19999 ],
            ["id" => 22, "name" => "Bosnian", "endonym" => "bosanski jezik", "abbreviation2" => "bs", "abbreviation3" => "bos", "status"=>1, "position" => 19999 ],
            ["id" => 23, "name" => "Breton", "endonym" => "brezhoneg", "abbreviation2" => "br", "abbreviation3" => "bre", "status"=>1, "position" => 19999 ],
            ["id" => 24, "name" => "Bulgarian", "endonym" => "български език", "abbreviation2" => "bg", "abbreviation3" => "bul", "status"=>1, "position" => 19999 ],
            ["id" => 25, "name" => "Burmese", "endonym" => "ဗမာစာ", "abbreviation2" => "my", "abbreviation3" => "mya", "status"=>1, "position" => 19999 ],
            ["id" => 26, "name" => "Catalan, Valencian", "endonym" => "català, valencià", "abbreviation2" => "ca", "abbreviation3" => "cat", "status"=>1, "position" => 19999 ],
            ["id" => 27, "name" => "Chamorro", "endonym" => "Chamoru", "abbreviation2" => "ch", "abbreviation3" => "cha", "status"=>1, "position" => 19999 ],
            ["id" => 28, "name" => "Chechen", "endonym" => "нохчийн мотт", "abbreviation2" => "ce", "abbreviation3" => "che", "status"=>1, "position" => 19999 ],
            ["id" => 29, "name" => "Chichewa, Chewa, Nyanja", "endonym" => "chiCheŵa, chinyanja", "abbreviation2" => "ny", "abbreviation3" => "nya", "status"=>1, "position" => 19999 ],
            ["id" => 30, "name" => "Chinese", "endonym" => "中文 (Zhōngwén), 汉语, 漢語", "abbreviation2" => "zh", "abbreviation3" => "zho", "status"=>1, "position" => 19999 ],
            ["id" => 31, "name" => "Chuvash", "endonym" => "чӑваш чӗлхи", "abbreviation2" => "cv", "abbreviation3" => "chv", "status"=>1, "position" => 19999 ],
            ["id" => 32, "name" => "Cornish", "endonym" => "Kernewek", "abbreviation2" => "kw", "abbreviation3" => "cor", "status"=>1, "position" => 19999 ],
            ["id" => 33, "name" => "Corsican", "endonym" => "corsu, lingua corsa", "abbreviation2" => "co", "abbreviation3" => "cos", "status"=>1, "position" => 19999 ],
            ["id" => 34, "name" => "Cree", "endonym" => "ᓀᐦᐃᔭᐍᐏᐣ", "abbreviation2" => "cr", "abbreviation3" => "cre", "status"=>1, "position" => 19999 ],
            ["id" => 35, "name" => "Croatian", "endonym" => "hrvatski jezik", "abbreviation2" => "hr", "abbreviation3" => "hrv", "status"=>1, "position" => 19999 ],
            ["id" => 36, "name" => "Czech", "endonym" => "čeština, český jazyk", "abbreviation2" => "cs", "abbreviation3" => "ces", "status"=>1, "position" => 19999 ],
            ["id" => 37, "name" => "Danish", "endonym" => "dansk", "abbreviation2" => "da", "abbreviation3" => "dan", "status"=>1, "position" => 19999 ],
            ["id" => 38, "name" => "Divehi, Dhivehi, Maldivian", "endonym" => "ދިވެހި", "abbreviation2" => "dv", "abbreviation3" => "div", "status"=>1, "position" => 19999 ],
            ["id" => 39, "name" => "Dutch", "endonym" => "Nederlands", "abbreviation2" => "nl", "abbreviation3" => "nld", "status"=>1, "position" => 19999 ],
            ["id" => 40, "name" => "Dzongkha", "endonym" => "རྫོང་ཁ", "abbreviation2" => "dz", "abbreviation3" => "dzo", "status"=>1, "position" => 19999 ],
            ["id" => 41, "name" => "English", "endonym" => "English", "abbreviation2" => "en", "abbreviation3" => "eng", "status"=>1, "position" => 4 ],
            ["id" => 42, "name" => "Esperanto", "endonym" => "Esperanto", "abbreviation2" => "eo", "abbreviation3" => "epo", "status"=>1, "position" => 19999 ],
            ["id" => 43, "name" => "Estonian", "endonym" => "eesti, eesti keel", "abbreviation2" => "et", "abbreviation3" => "est", "status"=>1, "position" => 19999 ],
            ["id" => 44, "name" => "Ewe", "endonym" => "Eʋegbe", "abbreviation2" => "ee", "abbreviation3" => "ewe", "status"=>1, "position" => 19999 ],
            ["id" => 45, "name" => "Faroese", "endonym" => "føroyskt", "abbreviation2" => "fo", "abbreviation3" => "fao", "status"=>1, "position" => 19999 ],
            ["id" => 46, "name" => "Fijian", "endonym" => "vosa Vakaviti", "abbreviation2" => "fj", "abbreviation3" => "fij", "status"=>1, "position" => 19999 ],
            ["id" => 47, "name" => "Finnish", "endonym" => "suomi, suomen kieli", "abbreviation2" => "fi", "abbreviation3" => "fin", "status"=>1, "position" => 19999 ],
            ["id" => 48, "name" => "French", "endonym" => "Français", "abbreviation2" => "fr", "abbreviation3" => "fra", "status"=>1, "position" => 5 ],
            ["id" => 49, "name" => "Fulah", "endonym" => "Fulfulde, Pulaar, Pular", "abbreviation2" => "ff", "abbreviation3" => "ful", "status"=>1, "position" => 19999 ],
            ["id" => 50, "name" => "Galician", "endonym" => "Galego", "abbreviation2" => "gl", "abbreviation3" => "glg", "status"=>1, "position" => 19999 ],
            ["id" => 51, "name" => "Georgian", "endonym" => "ქართული", "abbreviation2" => "ka", "abbreviation3" => "kat", "status"=>1, "position" => 19999 ],
            ["id" => 52, "name" => "German", "endonym" => "Deutsch", "abbreviation2" => "de", "abbreviation3" => "deu", "status"=>1, "position" => 6 ],
            ["id" => 53, "name" => "Greek", "endonym" => "ελληνικά", "abbreviation2" => "el", "abbreviation3" => "ell", "status"=>1, "position" => 19999 ],
            ["id" => 54, "name" => "Guarani", "endonym" => "Avañe'ẽ", "abbreviation2" => "gn", "abbreviation3" => "grn", "status"=>1, "position" => 19999 ],
            ["id" => 55, "name" => "Gujarati", "endonym" => "ગુજરાતી", "abbreviation2" => "gu", "abbreviation3" => "guj", "status"=>1, "position" => 19999 ],
            ["id" => 56, "name" => "Haitian, Haitian Creole", "endonym" => "Kreyòl ayisyen", "abbreviation2" => "ht", "abbreviation3" => "hat", "status"=>1, "position" => 19999 ],
            ["id" => 57, "name" => "Hausa", "endonym" => "(Hausa) هَوُسَ", "abbreviation2" => "ha", "abbreviation3" => "hau", "status"=>1, "position" => 19999 ],
            ["id" => 58, "name" => "Hebrew", "endonym" => "עברית", "abbreviation2" => "he", "abbreviation3" => "heb", "status"=>1, "position" => 19999 ],
            ["id" => 59, "name" => "Herero", "endonym" => "Otjiherero", "abbreviation2" => "hz", "abbreviation3" => "her", "status"=>1, "position" => 19999 ],
            ["id" => 60, "name" => "Hindi", "endonym" => "हिन्दी, हिंदी", "abbreviation2" => "hi", "abbreviation3" => "hin", "status"=>1, "position" => 19999 ],
            ["id" => 61, "name" => "Hiri Motu", "endonym" => "Hiri Motu", "abbreviation2" => "ho", "abbreviation3" => "hmo", "status"=>1, "position" => 19999 ],
            ["id" => 62, "name" => "Hungarian", "endonym" => "magyar", "abbreviation2" => "hu", "abbreviation3" => "hun", "status"=>1, "position" => 19999 ],
            ["id" => 63, "name" => "Indonesian", "endonym" => "Bahasa Indonesia", "abbreviation2" => "id", "abbreviation3" => "ind", "status"=>1, "position" => 19999 ],
            ["id" => 64, "name" => "Irish", "endonym" => "Gaeilge", "abbreviation2" => "ga", "abbreviation3" => "gle", "status"=>1, "position" => 19999 ],
            ["id" => 65, "name" => "Igbo", "endonym" => "Asụsụ Igbo", "abbreviation2" => "ig", "abbreviation3" => "ibo", "status"=>1, "position" => 19999 ],
            ["id" => 66, "name" => "Inupiaq", "endonym" => "Iñupiaq, Iñupiatun", "abbreviation2" => "ik", "abbreviation3" => "ipk", "status"=>1, "position" => 19999 ],
            ["id" => 67, "name" => "Ido", "endonym" => "Ido", "abbreviation2" => "io", "abbreviation3" => "ido", "status"=>1, "position" => 19999 ],
            ["id" => 68, "name" => "Icelandic", "endonym" => "Íslenska", "abbreviation2" => "is", "abbreviation3" => "isl", "status"=>1, "position" => 19999 ],
            ["id" => 69, "name" => "Italian", "endonym" => "Italiano", "abbreviation2" => "it", "abbreviation3" => "ita", "status"=>1, "position" => 19999 ],
            ["id" => 70, "name" => "Inuktitut", "endonym" => "ᐃᓄᒃᑎᑐᑦ", "abbreviation2" => "iu", "abbreviation3" => "iku", "status"=>1, "position" => 19999 ],
            ["id" => 71, "name" => "Japanese", "endonym" => "日本語 (にほんご)", "abbreviation2" => "ja", "abbreviation3" => "jpn", "status"=>1, "position" => 19999 ],
            ["id" => 72, "name" => "Javanese", "endonym" => "ꦧꦱꦗꦮ, Basa Jawa", "abbreviation2" => "jv", "abbreviation3" => "jav", "status"=>1, "position" => 19999 ],
            ["id" => 73, "name" => "Kalaallisut, Greenlandic", "endonym" => "kalaallisut, kalaallit oqaasii", "abbreviation2" => "kl", "abbreviation3" => "kal", "status"=>1, "position" => 19999 ],
            ["id" => 74, "name" => "Kannada", "endonym" => "ಕನ್ನಡ", "abbreviation2" => "kn", "abbreviation3" => "kan", "status"=>1, "position" => 19999 ],
            ["id" => 75, "name" => "Kanuri", "endonym" => "Kanuri", "abbreviation2" => "kr", "abbreviation3" => "kau", "status"=>1, "position" => 19999 ],
            ["id" => 76, "name" => "Kashmiri", "endonym" => "कश्मीरी, كشميري‎", "abbreviation2" => "ks", "abbreviation3" => "kas", "status"=>1, "position" => 19999 ],
            ["id" => 77, "name" => "Kazakh", "endonym" => "қазақ тілі", "abbreviation2" => "kk", "abbreviation3" => "kaz", "status"=>1, "position" => 19999 ],
            ["id" => 78, "name" => "Central Khmer", "endonym" => "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ", "abbreviation2" => "km", "abbreviation3" => "khm", "status"=>1, "position" => 19999 ],
            ["id" => 79, "name" => "Kikuyu, Gikuyu", "endonym" => "Gĩkũyũ", "abbreviation2" => "ki", "abbreviation3" => "kik", "status"=>1, "position" => 19999 ],
            ["id" => 80, "name" => "Kinyarwanda", "endonym" => "Ikinyarwanda", "abbreviation2" => "rw", "abbreviation3" => "kin", "status"=>1, "position" => 19999 ],
            ["id" => 81, "name" => "Kirghiz, Kyrgyz", "endonym" => "Кыргызча, Кыргыз тили", "abbreviation2" => "ky", "abbreviation3" => "kir", "status"=>1, "position" => 19999 ],
            ["id" => 82, "name" => "Komi", "endonym" => "коми кыв", "abbreviation2" => "kv", "abbreviation3" => "kom", "status"=>1, "position" => 19999 ],
            ["id" => 83, "name" => "Kongo", "endonym" => "Kikongo", "abbreviation2" => "kg", "abbreviation3" => "kon", "status"=>1, "position" => 19999 ],
            ["id" => 84, "name" => "Korean", "endonym" => "한국어", "abbreviation2" => "ko", "abbreviation3" => "kor", "status"=>1, "position" => 19999 ],
            ["id" => 85, "name" => "Kurdish", "endonym" => "Kurdî, کوردی‎", "abbreviation2" => "ku", "abbreviation3" => "kur", "status"=>1, "position" => 19999 ],
            ["id" => 86, "name" => "Kuanyama", "endonym" => "Kuanyama", "abbreviation2" => "kj", "abbreviation3" => "kua", "status"=>1, "position" => 19999 ],
            ["id" => 87, "name" => "Latin", "endonym" => "latine, lingua latina", "abbreviation2" => "la", "abbreviation3" => "lat", "status"=>1, "position" => 19999 ],
            ["id" => 88, "name" => "Luxembourgish", "endonym" => "Lëtzebuergesch", "abbreviation2" => "lb", "abbreviation3" => "ltz", "status"=>1, "position" => 19999 ],
            ["id" => 89, "name" => "Ganda", "endonym" => "Luganda", "abbreviation2" => "lg", "abbreviation3" => "lug", "status"=>1, "position" => 19999 ],
            ["id" => 90, "name" => "Limburgan", "endonym" => "Limburgs", "abbreviation2" => "li", "abbreviation3" => "lim", "status"=>1, "position" => 19999 ],
            ["id" => 91, "name" => "Lingala", "endonym" => "Lingála", "abbreviation2" => "ln", "abbreviation3" => "lin", "status"=>1, "position" => 19999 ],
            ["id" => 92, "name" => "Lao", "endonym" => "ພາສາລາວ", "abbreviation2" => "lo", "abbreviation3" => "lao", "status"=>1, "position" => 19999 ],
            ["id" => 93, "name" => "Lithuanian", "endonym" => "lietuvių kalba", "abbreviation2" => "lt", "abbreviation3" => "lit", "status"=>1, "position" => 19999 ],
            ["id" => 94, "name" => "Luba-Katanga", "endonym" => "Kiluba", "abbreviation2" => "lu", "abbreviation3" => "lub", "status"=>1, "position" => 19999 ],
            ["id" => 95, "name" => "Latvian", "endonym" => "latviešu valoda", "abbreviation2" => "lv", "abbreviation3" => "lav", "status"=>1, "position" => 19999 ],
            ["id" => 96, "name" => "Manx", "endonym" => "Gaelg, Gailck", "abbreviation2" => "gv", "abbreviation3" => "glv", "status"=>1, "position" => 19999 ],
            ["id" => 97, "name" => "Macedonian", "endonym" => "македонски јазик", "abbreviation2" => "mk", "abbreviation3" => "mkd", "status"=>1, "position" => 19999 ],
            ["id" => 98, "name" => "Malagasy", "endonym" => "fiteny malagasy", "abbreviation2" => "mg", "abbreviation3" => "mlg", "status"=>1, "position" => 19999 ],
            ["id" => 99, "name" => "Malay", "endonym" => "Bahasa Melayu, بهاس ملايو‎", "abbreviation2" => "ms", "abbreviation3" => "msa", "status"=>1, "position" => 19999 ],
            ["id" => 100, "name" => "Malayalam", "endonym" => "മലയാളം", "abbreviation2" => "ml", "abbreviation3" => "mal", "status"=>1, "position" => 19999 ],
            ["id" => 101, "name" => "Maltese", "endonym" => "Malti", "abbreviation2" => "mt", "abbreviation3" => "mlt", "status"=>1, "position" => 19999 ],
            ["id" => 102, "name" => "Maori", "endonym" => "te reo Māori", "abbreviation2" => "mi", "abbreviation3" => "mri", "status"=>1, "position" => 19999 ],
            ["id" => 103, "name" => "Marathi", "endonym" => "मराठी", "abbreviation2" => "mr", "abbreviation3" => "mar", "status"=>1, "position" => 19999 ],
            ["id" => 104, "name" => "Marshallese", "endonym" => "Kajin M̧ajeļ", "abbreviation2" => "mh", "abbreviation3" => "mah", "status"=>1, "position" => 19999 ],
            ["id" => 105, "name" => "Mongolian", "endonym" => "Монгол хэл", "abbreviation2" => "mn", "abbreviation3" => "mon", "status"=>1, "position" => 19999 ],
            ["id" => 106, "name" => "Nauru", "endonym" => "Dorerin Naoero", "abbreviation2" => "na", "abbreviation3" => "nau", "status"=>1, "position" => 19999 ],
            ["id" => 107, "name" => "Navajo, Navaho", "endonym" => "Diné bizaad", "abbreviation2" => "nv", "abbreviation3" => "nav", "status"=>1, "position" => 19999 ],
            ["id" => 108, "name" => "North Ndebele", "endonym" => "isiNdebele", "abbreviation2" => "nd", "abbreviation3" => "nde", "status"=>1, "position" => 19999 ],
            ["id" => 109, "name" => "Nepali", "endonym" => "नेपाली", "abbreviation2" => "ne", "abbreviation3" => "nep", "status"=>1, "position" => 19999 ],
            ["id" => 110, "name" => "Ndonga", "endonym" => "Owambo", "abbreviation2" => "ng", "abbreviation3" => "ndo", "status"=>1, "position" => 19999 ],
            ["id" => 111, "name" => "Norwegian Bokmål", "endonym" => "Norsk Bokmål", "abbreviation2" => "nb", "abbreviation3" => "nob", "status"=>1, "position" => 19999 ],
            ["id" => 112, "name" => "Norwegian Nynorsk", "endonym" => "Norsk Nynorsk", "abbreviation2" => "nn", "abbreviation3" => "nno", "status"=>1, "position" => 19999 ],
            ["id" => 113, "name" => "Norwegian", "endonym" => "Norsk", "abbreviation2" => "no", "abbreviation3" => "nor", "status"=>1, "position" => 19999 ],
            ["id" => 114, "name" => "Sichuan Yi, Nuosu", "endonym" => "ꆈꌠ꒿ Nuosuhxop", "abbreviation2" => "ii", "abbreviation3" => "iii", "status"=>1, "position" => 19999 ],
            ["id" => 115, "name" => "South Ndebele", "endonym" => "isiNdebele", "abbreviation2" => "nr", "abbreviation3" => "nbl", "status"=>1, "position" => 19999 ],
            ["id" => 116, "name" => "Occitan", "endonym" => "occitan, lenga d'òc", "abbreviation2" => "oc", "abbreviation3" => "oci", "status"=>1, "position" => 19999 ],
            ["id" => 117, "name" => "Ojibwa", "endonym" => "ᐊᓂᔑᓈᐯᒧᐎᓐ", "abbreviation2" => "oj", "abbreviation3" => "oji", "status"=>1, "position" => 19999 ],
            ["id" => 118, "name" => "Slavonic", "endonym" => "ѩзыкъ словѣньскъ", "abbreviation2" => "cu", "abbreviation3" => "chu", "status"=>1, "position" => 19999 ],
            ["id" => 119, "name" => "Oromo", "endonym" => "Afaan Oromoo", "abbreviation2" => "om", "abbreviation3" => "orm", "status"=>1, "position" => 19999 ],
            ["id" => 120, "name" => "Oriya", "endonym" => "ଓଡ଼ିଆ", "abbreviation2" => "or", "abbreviation3" => "ori", "status"=>1, "position" => 19999 ],
            ["id" => 121, "name" => "Ossetian, Ossetic", "endonym" => "ирон æвзаг", "abbreviation2" => "os", "abbreviation3" => "oss", "status"=>1, "position" => 19999 ],
            ["id" => 122, "name" => "Punjabi, Panjabi", "endonym" => "ਪੰਜਾਬੀ, پنجابی‎", "abbreviation2" => "pa", "abbreviation3" => "pan", "status"=>1, "position" => 19999 ],
            ["id" => 123, "name" => "Pali", "endonym" => "पालि, पाळि", "abbreviation2" => "pi", "abbreviation3" => "pli", "status"=>1, "position" => 19999 ],
            ["id" => 124, "name" => "Persian", "endonym" => "فارسی", "abbreviation2" => "fa", "abbreviation3" => "fas", "status"=>1, "position" => 19999 ],
            ["id" => 125, "name" => "Polish", "endonym" => "język polski, polszczyzna", "abbreviation2" => "pl", "abbreviation3" => "pol", "status"=>1, "position" => 19999 ],
            ["id" => 126, "name" => "Pashto, Pushto", "endonym" => "پښتو", "abbreviation2" => "ps", "abbreviation3" => "pus", "status"=>1, "position" => 19999 ],
            ["id" => 127, "name" => "Portuguese", "endonym" => "Português", "abbreviation2" => "pt", "abbreviation3" => "por", "status"=>1, "position" => 19999 ],
            ["id" => 128, "name" => "Quechua", "endonym" => "Runa Simi, Kichwa", "abbreviation2" => "qu", "abbreviation3" => "que", "status"=>1, "position" => 19999 ],
            ["id" => 129, "name" => "Romansh", "endonym" => "Rumantsch Grischun", "abbreviation2" => "rm", "abbreviation3" => "roh", "status"=>1, "position" => 19999 ],
            ["id" => 130, "name" => "Rundi", "endonym" => "Ikirundi", "abbreviation2" => "rn", "abbreviation3" => "run", "status"=>1, "position" => 19999 ],
            ["id" => 131, "name" => "Romanian", "endonym" => "Română", "abbreviation2" => "ro", "abbreviation3" => "ron", "status"=>1, "position" => 1 ],
            ["id" => 132, "name" => "Russian", "endonym" => "русский", "abbreviation2" => "ru", "abbreviation3" => "rus", "status"=>1, "position" => 3 ],
            ["id" => 133, "name" => "Sanskrit", "endonym" => "संस्कृतम्", "abbreviation2" => "sa", "abbreviation3" => "san", "status"=>1, "position" => 19999 ],
            ["id" => 134, "name" => "Sardinian", "endonym" => "sardu", "abbreviation2" => "sc", "abbreviation3" => "srd", "status"=>1, "position" => 19999 ],
            ["id" => 135, "name" => "Sindhi", "endonym" => "सिन्धी, سنڌي، سندھی‎", "abbreviation2" => "sd", "abbreviation3" => "snd", "status"=>1, "position" => 19999 ],
            ["id" => 136, "name" => "Northern Sami", "endonym" => "Davvisámegiella", "abbreviation2" => "se", "abbreviation3" => "sme", "status"=>1, "position" => 19999 ],
            ["id" => 137, "name" => "Samoan", "endonym" => "gagana fa'a Samoa", "abbreviation2" => "sm", "abbreviation3" => "smo", "status"=>1, "position" => 19999 ],
            ["id" => 138, "name" => "Sango", "endonym" => "yângâ tî sängö", "abbreviation2" => "sg", "abbreviation3" => "sag", "status"=>1, "position" => 19999 ],
            ["id" => 139, "name" => "Serbian", "endonym" => "српски језик", "abbreviation2" => "sr", "abbreviation3" => "srp", "status"=>1, "position" => 19999 ],
            ["id" => 140, "name" => "Gaelic", "endonym" => "Gàidhlig", "abbreviation2" => "gd", "abbreviation3" => "gla", "status"=>1, "position" => 19999 ],
            ["id" => 141, "name" => "Shona", "endonym" => "chiShona", "abbreviation2" => "sn", "abbreviation3" => "sna", "status"=>1, "position" => 19999 ],
            ["id" => 142, "name" => "Sinhala, Sinhalese", "endonym" => "සිංහල", "abbreviation2" => "si", "abbreviation3" => "sin", "status"=>1, "position" => 19999 ],
            ["id" => 143, "name" => "Slovak", "endonym" => "Slovenčina, Slovenský Jazyk", "abbreviation2" => "sk", "abbreviation3" => "slk", "status"=>1, "position" => 19999 ],
            ["id" => 144, "name" => "Slovenian", "endonym" => "Slovenski Jezik, Slovenščina", "abbreviation2" => "sl", "abbreviation3" => "slv", "status"=>1, "position" => 19999 ],
            ["id" => 145, "name" => "Somali", "endonym" => "Soomaaliga, af Soomaali", "abbreviation2" => "so", "abbreviation3" => "som", "status"=>1, "position" => 19999 ],
            ["id" => 146, "name" => "Southern Sotho", "endonym" => "Sesotho", "abbreviation2" => "st", "abbreviation3" => "sot", "status"=>1, "position" => 19999 ],
            ["id" => 147, "name" => "Spanish, Castilian", "endonym" => "Español", "abbreviation2" => "es", "abbreviation3" => "spa", "status"=>1, "position" => 19999 ],
            ["id" => 148, "name" => "Sundanese", "endonym" => "Basa Sunda", "abbreviation2" => "su", "abbreviation3" => "sun", "status"=>1, "position" => 19999 ],
            ["id" => 149, "name" => "Swahili", "endonym" => "Kiswahili", "abbreviation2" => "sw", "abbreviation3" => "swa", "status"=>1, "position" => 19999 ],
            ["id" => 150, "name" => "Swati", "endonym" => "SiSwati", "abbreviation2" => "ss", "abbreviation3" => "ssw", "status"=>1, "position" => 19999 ],
            ["id" => 151, "name" => "Swedish", "endonym" => "Svenska", "abbreviation2" => "sv", "abbreviation3" => "swe", "status"=>1, "position" => 19999 ],
            ["id" => 152, "name" => "Tamil", "endonym" => "தமிழ்", "abbreviation2" => "ta", "abbreviation3" => "tam", "status"=>1, "position" => 19999 ],
            ["id" => 153, "name" => "Telugu", "endonym" => "తెలుగు", "abbreviation2" => "te", "abbreviation3" => "tel", "status"=>1, "position" => 19999 ],
            ["id" => 154, "name" => "Tajik", "endonym" => "тоҷикӣ, toçikī, تاجیکی‎", "abbreviation2" => "tg", "abbreviation3" => "tgk", "status"=>1, "position" => 19999 ],
            ["id" => 155, "name" => "Thai", "endonym" => "ไทย", "abbreviation2" => "th", "abbreviation3" => "tha", "status"=>1, "position" => 19999 ],
            ["id" => 156, "name" => "Tigrinya", "endonym" => "ትግርኛ", "abbreviation2" => "ti", "abbreviation3" => "tir", "status"=>1, "position" => 19999 ],
            ["id" => 157, "name" => "Tibetan", "endonym" => "བོད་ཡིག", "abbreviation2" => "bo", "abbreviation3" => "bod", "status"=>1, "position" => 19999 ],
            ["id" => 158, "name" => "Turkmen", "endonym" => "Türkmen, Түркмен", "abbreviation2" => "tk", "abbreviation3" => "tuk", "status"=>1, "position" => 19999 ],
            ["id" => 159, "name" => "Tagalog", "endonym" => "Wikang Tagalog", "abbreviation2" => "tl", "abbreviation3" => "tgl", "status"=>1, "position" => 19999 ],
            ["id" => 160, "name" => "Tswana", "endonym" => "Setswana", "abbreviation2" => "tn", "abbreviation3" => "tsn", "status"=>1, "position" => 19999 ],
            ["id" => 161, "name" => "Tonga", "endonym" => "Faka Tonga", "abbreviation2" => "to", "abbreviation3" => "ton", "status"=>1, "position" => 19999 ],
            ["id" => 162, "name" => "Turkish", "endonym" => "Türkçe", "abbreviation2" => "tr", "abbreviation3" => "tur", "status"=>1, "position" => 19999 ],
            ["id" => 163, "name" => "Tsonga", "endonym" => "Xitsonga", "abbreviation2" => "ts", "abbreviation3" => "tso", "status"=>1, "position" => 19999 ],
            ["id" => 164, "name" => "Tatar", "endonym" => "татар теле, tatar tele", "abbreviation2" => "tt", "abbreviation3" => "tat", "status"=>1, "position" => 19999 ],
            ["id" => 165, "name" => "Twi", "endonym" => "Twi", "abbreviation2" => "tw", "abbreviation3" => "twi", "status"=>1, "position" => 19999 ],
            ["id" => 166, "name" => "Tahitian", "endonym" => "Reo Tahiti", "abbreviation2" => "ty", "abbreviation3" => "tah", "status"=>1, "position" => 19999 ],
            ["id" => 167, "name" => "Uighur, Uyghur", "endonym" => "ئۇيغۇرچە‎, Uyghurche", "abbreviation2" => "ug", "abbreviation3" => "uig", "status"=>1, "position" => 19999 ],
            ["id" => 168, "name" => "Ukrainian", "endonym" => "Українська", "abbreviation2" => "uk", "abbreviation3" => "ukr", "status"=>1, "position" => 2 ],
            ["id" => 169, "name" => "Urdu", "endonym" => "اردو", "abbreviation2" => "ur", "abbreviation3" => "urd", "status"=>1, "position" => 19999 ],
            ["id" => 170, "name" => "Uzbek", "endonym" => "Oʻzbek, Ўзбек, أۇزبېك‎", "abbreviation2" => "uz", "abbreviation3" => "uzb", "status"=>1, "position" => 19999 ],
            ["id" => 171, "name" => "Venda", "endonym" => "Tshivenḓa", "abbreviation2" => "ve", "abbreviation3" => "ven", "status"=>1, "position" => 19999 ],
            ["id" => 172, "name" => "Vietnamese", "endonym" => "Tiếng Việt", "abbreviation2" => "vi", "abbreviation3" => "vie", "status"=>1, "position" => 19999 ],
            ["id" => 173, "name" => "Volapük", "endonym" => "Volapük", "abbreviation2" => "vo", "abbreviation3" => "vol", "status"=>1, "position" => 19999 ],
            ["id" => 174, "name" => "Walloon", "endonym" => "Walon", "abbreviation2" => "wa", "abbreviation3" => "wln", "status"=>1, "position" => 19999 ],
            ["id" => 175, "name" => "Welsh", "endonym" => "Cymraeg", "abbreviation2" => "cy", "abbreviation3" => "cym", "status"=>1, "position" => 19999 ],
            ["id" => 176, "name" => "Wolof", "endonym" => "Wollof", "abbreviation2" => "wo", "abbreviation3" => "wol", "status"=>1, "position" => 19999 ],
            ["id" => 177, "name" => "Western Frisian", "endonym" => "Frysk", "abbreviation2" => "fy", "abbreviation3" => "fry", "status"=>1, "position" => 19999 ],
            ["id" => 178, "name" => "Xhosa", "endonym" => "isiXhosa", "abbreviation2" => "xh", "abbreviation3" => "xho", "status"=>1, "position" => 19999 ],
            ["id" => 179, "name" => "Yiddish", "endonym" => "ייִדיש", "abbreviation2" => "yi", "abbreviation3" => "yid", "status"=>1, "position" => 19999 ],
            ["id" => 180, "name" => "Yoruba", "endonym" => "Yorùbá", "abbreviation2" => "yo", "abbreviation3" => "yor", "status"=>1, "position" => 19999 ],
            ["id" => 181, "name" => "Zhuang, Chuang", "endonym" => "Saɯ cueŋƅ, Saw cuengh", "abbreviation2" => "za", "abbreviation3" => "zha", "status"=>1, "position" => 19999 ],
            ["id" => 182, "name" => "Zulu", "endonym" => "isiZulu", "abbreviation2" => "zu", "abbreviation3" => "zul", "status"=>1, "position" => 19999 ],
        ];

        foreach ($data as $row){
            \App\Language::create($row);
        }
    }
}
