version: '3.7'

services:
  database:
    build:
      context: .docker/dev/mysql
      dockerfile: Dockerfile
    container_name: helpforhealth_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: developer
    networks:
      - helpforhealth.local
    expose:
      - 3306
    ports:
      - 33066:3306

  webserver:
    container_name: helpforhealth_web
    build:
      dockerfile: .docker/dev/webserver/Dockerfile
      context: ./
    volumes:
      - ./:/app
    links:
      - database
    networks:
      - helpforhealth.local
    expose:
      - 80
    ports:
      - 80:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: helpforhealth_phpmyadmin
    environment:
      PMA_USER: root
      PMA_PASSWORD: developer
    networks:
      - helpforhealth.local
    links:
      - database:db
    expose:
      - 80
    ports:
      - 8080:80

networks:
  helpforhealth.local:
    driver: bridge
