version: '3.7'

services:
  nginx:
    image: library/nginx:stable-alpine
    volumes:
      - ./public:/var/www/html/public:ro,delegated
      - ./.docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro,cached
    ports:
      - 80:80

  php:
    build:
      dockerfile: .docker/php/Dockerfile
      context: .
      target: dev_stage
    volumes:
    - ./:/var/www/html
    - ./.docker/php/dev/zz-xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini:ro,cached
    - ./.docker/php/dev/zzz-opcache-dev.ini:/usr/local/etc/php/conf.d/zzz-opcache-dev.ini:ro,cache

  nodejs:
    image: node:16-alpine
    working_dir: /app
    volumes:
    - ./:/app
    command: ["sleep", "infinity"]

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: developer
      MYSQL_DATABSE: unacoperis
    ports:
      - 33066:3306
    volumes:
    - ./.docker/mysql/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: developer
    ports:
      - 8080:80
