version: "3.7"

services:
  php:
    build:
      dockerfile: .docker/php/Dockerfile
      target: build
      context: .
    env_file: .env
    environment:
      PHP_OPCACHE_ENABLE: 0
    volumes:
      - ./:/var/www:delegated
    ports:
      - "80:8080"
    depends_on:
      - database

  nodejs:
    image: node:16-alpine
    working_dir: /app
    environment:
      HOME: /tmp/npm
    volumes:
      - ./:/app:delegated
    command: >
      sh -c "
        npm ci &&
        npm run development
      "

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 33066:3306
    volumes:
      - database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file: .env
    environment:
      PMA_HOST: database
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8080:80

volumes:
  database:
    driver: local
