version: "3.7"

services:
  php:
    image: code4romania/un-acoperis:staging
    labels:
      - com.centurylinklabs.watchtower.enable=true
    env_file: .env
    environment:
      PHP_OPCACHE_ENABLE: 0
    ports:
      - "80:8080"
    depends_on:
      - database

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 33066:3306
    volumes:
      - database:/var/lib/mysql

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --include-restarting --label-enable --cleanup

volumes:
  database:
    driver: local
