version: "3.7"

services:
  php:
    build:
      dockerfile: .docker/php/Dockerfile
    environment:
      APP_ENV: local
    volumes:
      - ./:/var/www:delegated
    ports:
      - "80:8080"

  nodejs:
    image: node:16-alpine
    working_dir: /app
    environment:
      HOME: /tmp/npm
    volumes:
      - ./:/app:delegated
    command: ["sleep", "infinity"]

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: developer
      MYSQL_DATABASE: unacoperis
    ports:
      - 33066:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: developer
    ports:
      - 8080:80
