@formField('wysiwyg', [
    'name' => 'paragraph',
    'type' => 'textarea',
    'translated' => true,
    'maxlength' => 10000,
    'toolbarOptions' => [
        ['header' => [2, 3, 4, 5, 6, false]],
        'bold',
        'italic',
        'underline',
        'strike',
        ["script" => "super"],
        ["script" => "sub"],
        "blockquote",
        "code-block",
        ['list' => 'ordered'],
        ['list' => 'bullet'],
        ['indent' => '-1'],
        ['indent' => '+1'],
        ["align" => []],
        ["direction" => "rtl"],
        'link',
        "clean",
    ],
    'label' => 'Paragraph',
    'placeholder' => 'Placeholder',
    'maxlength' => 200,
    'editSource' => true,
    'note' => 'Note',
])
