apiVersion: v1
kind: Service
metadata:
  name: un-acoperis-service
spec:
  type: ClusterIP
  selector:
    app: un-acoperis
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
